### ISSUE TITLE
amazonhop.co

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1153]
### Comments

This domain is being used for a smishing campaign. A screenshot of a lure that was received earlier today is included in the screenshots.  The domain has been reported to the registrar as well as to Amazon security.

### Wildcard domain records

```CSV
amazonhop.co|phishing,typosquatting
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/6e76e784-ed0b-4946-b23b-f5a9df6e2c72)
![image](https://github.com/user-attachments/assets/5be3b213-d9ef-479f-b29d-e55dcef62bee)

</details>

### Links to external sources

```CSS
https://urlscan.io/result/fd39fe19-47b9-4492-9d09-5a08cb77d709
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Hey @g0d33p3rsec Thanks for your commits, I've added this one to typosquatting as well, thought it looks legit

**Comment by g0d33p3rsec** [comment]
> Hey @g0d33p3rsec Thanks for your commits, I've added this one to typosquatting as well, thought it looks legit

good call.  The domain should be deactivated now.
![Screenshot 2024-09-27 090454](https://github.com/user-attachments/assets/423bad5a-4c36-499c-a81d-88738c2bf985)

**Comment by spirillen** [comment]
Super, thanks for taking your time to contact the DNS author to bring their attention to the issue. And you even had a good experience doing so.
