### ISSUE TITLE
himosteg.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1161]
### Comments

Related to MoneyBadger$ traffic distribution system.  See also: https://github.com/mitchellkrogza/phishing/pull/492

### Wildcard domain records

```CSV
himosteg.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![374747690-5318e95a-30b1-4836-a08f-bd2db808912f](https://github.com/user-attachments/assets/637e1598-f22d-4049-855d-363c33f28ab0)

</details>

### Links to external sources

```CSS
https://himosteg.xyz/auth.php 
https://urlscan.io/result/1bb682cd-e9d8-43fa-8222-ba8effe534fa/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by g0d33p3rsec** [comment]
@spirillen I'm not sure how to best categorize this and the other entries from https://github.com/mitchellkrogza/phishing/pull/492.  This page is a log in and likely C2 for the traffic distribution system being used to push fake virus notifications.

**Comment by spirillen** [comment]
Commented in https://kb.mypdns.org/issue/MTX-1162/himosteg.xyz#focus=Comments-4-229.0-0

If you update your profile there, you can get access to hidden issues as well for all mypdns project.

**Comment by g0d33p3rsec** [comment]
> Commented in https://kb.mypdns.org/issue/MTX-1162/himosteg.xyz#focus=Comments-4-229.0-0
> 
> If you update your profile there, you can get access to hidden issues as well for all mypdns project.

Cool, thanks.  I've signed up with the same display name as this account.  It looks like the username appended `.wwgj` to that.
