### ISSUE TITLE
kalestin.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1169]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
kalestin.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![4c992b82-f8e8-4190-a4ba-e5ca6076e4d6](https://github.com/user-attachments/assets/0d5652e9-f2aa-4847-8bf3-36e19152f2d6)

</details>

### Links to external sources

```CSS
https://kalestin.xyz/6/7.html
https://urlscan.io/result/4c992b82-f8e8-4190-a4ba-e5ca6076e4d6/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
