### ISSUE TITLE
ragimost.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1170]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
ragimost.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![e3f013e7-3f5f-41e6-8d32-8167477ba39c](https://github.com/user-attachments/assets/3239400e-6fc8-462f-9512-e77faad82e0d)

</details>

### Links to external sources

```CSS
https://ragimost.xyz/1/7.html
https://urlscan.io/result/e3f013e7-3f5f-41e6-8d32-8167477ba39c/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
