### ISSUE TITLE
avgs.fun

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1171]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
avgs.fun|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![44b08999-c2ac-4c62-a056-250b9d10e610](https://github.com/user-attachments/assets/2e26dc4a-75c3-4c83-b4c5-ab2c1644d729)

</details>

### Links to external sources

```CSS
https://avgs.fun/
https://urlscan.io/result/44b08999-c2ac-4c62-a056-250b9d10e610/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
