### ISSUE TITLE
daleesh.fun

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1172]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
daleesh.fun|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![cd6d3886-b992-4529-8bb1-be4c1e111e34](https://github.com/user-attachments/assets/a2dd226d-35ff-4ccc-b69f-9e6b5a000cdb)

</details>

### Links to external sources

```CSS
https://daleesh.fun/?key=
https://urlscan.io/result/cd6d3886-b992-4529-8bb1-be4c1e111e34/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
