### ISSUE TITLE
avastos.fun

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1173]
### Comments

This domain is redirecting to #1172 and related to the MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
avastos.fun|malicious,phishing,redirecting,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![cd6d3886-b992-4529-8bb1-be4c1e111e34](https://github.com/user-attachments/assets/476cf59f-5ec8-439b-8f04-a38ffd864301)

</details>

### Links to external sources

```CSS
http://www.avastos.fun/go/72864d68-322d-4564-9def-4c8314cf8caa?visitor=trusted
https://urlscan.io/result/cd6d3886-b992-4529-8bb1-be4c1e111e34/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
