### ISSUE TITLE
firengav.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1174]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
firengav.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![93274c92-76ec-4ef1-b8c4-2a3b6a68b5a3](https://github.com/user-attachments/assets/d235eed7-5aad-4377-831b-9b490ba660f5)

</details>

### Links to external sources

```CSS
https://firengav.xyz/13vk/7.html
https://urlscan.io/result/93274c92-76ec-4ef1-b8c4-2a3b6a68b5a3/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
