### ISSUE TITLE
dolaxabof.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1175]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
dolaxabof.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![c1c15684-df96-4429-8eb9-60992bef0066](https://github.com/user-attachments/assets/0b4cb6aa-f808-40af-a9be-8c9f4801a609)

</details>

### Links to external sources

```CSS
https://dolaxabof.xyz/12/7.html
https://urlscan.io/result/c1c15684-df96-4429-8eb9-60992bef0066/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
