### ISSUE TITLE
hugabedis.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1176]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
hugabedis.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![44db1e7f-f536-48ae-af52-ad36c5f1386f](https://github.com/user-attachments/assets/a4607a7a-0429-4c38-8511-d82c739d2654)

</details>

### Links to external sources

```CSS
https://hugabedis.xyz/13vk/7.html
https://urlscan.io/result/44db1e7f-f536-48ae-af52-ad36c5f1386f/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
