### ISSUE TITLE
mabikorst.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1177]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
mabikorst.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![a69ff476-a0e5-4623-be5d-2fc0e831963e](https://github.com/user-attachments/assets/65e7da21-deaf-4e21-bff1-41760e6b006d)

</details>

### Links to external sources

```CSS
https://mabikorst.xyz/13je/7.html
https://urlscan.io/result/a69ff476-a0e5-4623-be5d-2fc0e831963e/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
