### ISSUE TITLE
worldwidewebshield.info

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1178]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
worldwidewebshield.info|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![b799524b-d0e4-4d83-931e-f3c38b766e3b](https://github.com/user-attachments/assets/92025e24-7483-45d0-880a-90038d64cbba)

</details>

### Links to external sources

```CSS
https://hsll.worldwidewebshield.info/c/56f0a1ffcf55fe50?
https://urlscan.io/result/b799524b-d0e4-4d83-931e-f3c38b766e3b/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
