### ISSUE TITLE
alhocans.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1179]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
alhocans.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![02670bfe-373a-4934-bc38-27bb20dfb426](https://github.com/user-attachments/assets/d5651e60-6a3f-4319-ab8d-e72b914d41e9)

</details>

### Links to external sources

```CSS
https://alhocans.xyz/12wh/7.html
https://urlscan.io/result/02670bfe-373a-4934-bc38-27bb20dfb426/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
