### ISSUE TITLE
koruns.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1180]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
koruns.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![3958275f-fee0-4bee-bc11-c1abea6f1d02](https://github.com/user-attachments/assets/e46cd27f-f371-43ca-b02a-a5dc4874b66e)

</details>

### Links to external sources

```CSS
https://koruns.xyz/9/7.html
https://urlscan.io/result/3958275f-fee0-4bee-bc11-c1abea6f1d02/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
