### ISSUE TITLE
ilertonp.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1181]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
ilertonp.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![3fbe30e2-2e82-412a-b88a-a31403d40c93](https://github.com/user-attachments/assets/418ae8cb-6bf9-4bb8-9da3-490d0a1bf3b2)

</details>

### Links to external sources

```CSS
https://ilertonp.xyz/2Df/7.html
https://urlscan.io/result/3fbe30e2-2e82-412a-b88a-a31403d40c93/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
