### ISSUE TITLE
kusilong.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1182]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
kusilong.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![07a8c175-de83-4c90-8bcc-0dbb0e12c1d5](https://github.com/user-attachments/assets/8ccfd70d-fbe4-4988-ac86-e797487de646)

</details>

### Links to external sources

```CSS
https://kusilong.xyz/2/7.html
https://urlscan.io/result/07a8c175-de83-4c90-8bcc-0dbb0e12c1d5/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
