### ISSUE TITLE
neburfaw.xyz

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1183]
### Comments

Related to MoneyBadger$ traffic distribution system. See also: https://github.com/mitchellkrogza/phishing/pull/492 and https://github.com/mitchellkrogza/phishing/pull/493

### Wildcard domain records

```CSV
neburfaw.xyz|malicious,phishing,scamming
```

### Screenshots

<details><summary>Screenshot</summary>

![d88f0b23-65f2-4bef-929c-73a4767a9d0f](https://github.com/user-attachments/assets/ec43b44f-6b94-4654-b682-da92d43ca3af)

</details>

### Links to external sources

```CSS
https://neburfaw.xyz/13/7.html 
https://urlscan.io/result/d88f0b23-65f2-4bef-929c-73a4767a9d0f/
https://twitter.com/1ZRR4H/status/1685764738121175040
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
