### ISSUE TITLE
com-trackahc.top

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1184]
### Comments

This page is being used for a USPS delivery failure smishing campaign.

### Wildcard domain records

```CSV
com-trackahc.top|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/2459e1e7-ee75-4be0-9d32-31ea47741650)
![image](https://github.com/user-attachments/assets/23c30afd-9ce7-4a28-9334-94220c2825c7)

</details>

### Links to external sources

```CSS
https://usps.com-trackahc.top/l/ 
https://urlscan.io/result/88585569-2bf2-407e-b60c-c7ce004bc616/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Fixed in https://github.com/mypdns/matrix/commit/4e79dea08a242d73ddd36627f8ce23ce39aa1d1d
