### ISSUE TITLE
amazonaiy.co

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1186]
### Comments

I received a sms lure with a shortened link that resolved to this domain. The message was:

>   [AMAZ0N] The item you purchased has encountered an issue and has been adjusted by the seller. Please check for details. hxxps://t[.]ly/ps3bw?hui=xdPNDLBFNj

### Wildcard domain records

```CSV
amazonaiy.co|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![375804098-d7da5b19-61c4-449b-b515-df4f02c6c7e8](https://github.com/user-attachments/assets/23ac8f5d-46e5-4cfa-b30d-6a79c7d94f68)
![375804231-40bfdf3f-a0f0-4208-9b73-c910841cf262](https://github.com/user-attachments/assets/772f8422-2702-441e-8953-59176458a3cc)

</details>

### Links to external sources

```CSS
https://amazonaiy.co/?hui=xdPNDLBFNj
https://urlscan.io/result/33471298-3cd4-4591-ad5e-6d07f9c876f3/
https://urlscan.io/result/3603afa0-d630-4771-a2ce-4d91a4cbd1ed/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
I can not find any active phishing links / pages on this domain. I'm tempted to close it as fixed by the web host
