### ISSUE TITLE
leadslitmus.com

### ISSUE THREAD

**Issue by TechArea** [mypdns/matrix#1193]
### Comments

leadslitmus.com is a domain that seams to be used for phishing

### Wildcard domain records

```CSV
leadslitmus.com | phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![CleanShot 2024-10-17 at 19 18 15@2x](https://github.com/user-attachments/assets/d9ed83a4-d8bf-4220-b2cf-0a95943f8dc9)

</details>

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by TechArea** [comment]
I redacted my mail address and my FQDN.
Everything else is untouched.

Delivered-To: xxx@yyy.lol
Received: by 2002:ab2:5b8d:0:b0:20d:b360:5dbf with SMTP id e13csp636722lqk;
        Wed, 25 Sep 2024 14:04:03 -0700 (PDT)
X-Google-Smtp-Source: AGHT+IFgdt8wuta/KiLEm5mF9Gyuzwa4TR4aNINhM7tjJmaQl4XYsu6W+Uw1VvlzLZn/9sEi0qy8
X-Received: by 2002:a5d:648a:0:b0:368:3731:1613 with SMTP id ffacd0b85a97d-37cc2479f61mr3192432f8f.13.1727298243282;
        Wed, 25 Sep 2024 14:04:03 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1727298243; cv=none;
        d=google.com; s=arc-20240605;
        b=lHWPKZJ/wj72VDuHGNHY4Etat63SMGmlhO1MolsRup62KJDtODd91cTyG7HyRyzWS/
         LhV/RZy/MIEFStLDGbCLS3wG86joyGCIhxigLJillg7f+9cgenR3Tm1CQRvlCnrY1ueR
         cfB/NOe6mLeHrZu6Ww5FUH8zU8szeLZ0olu+Ygvw1fHW2ueZ700YwxwvKtYM4Gf3e+m5
         jqUYVmGbkjRUmtggCBeYR/BVU2bER7vLZzg4pGhLYInY+k6i99TX6MIZ0nUoDYt2UvTA
         d3BRIs6r82vGHRYXRnxXazVNyG+il+Yx0kQSsvW3X1BlpLvu9xqMZIafUviDT5R9zf79
         96/Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20240605;
        h=disposition-notification-to:content-language:thread-index
         :mime-version:message-id:date:subject:in-reply-to:references:to:from;
        bh=iX89txS57g2SxmICn7t6vs6Qvt4qGjPukf0KZVHd+1o=;
        fh=8Q4zZkLpu5biF4+eGnIdHR8dVK8WxR9iX+2yetQ9jB4=;
        b=QFPOWNB1fzqZ3U062N8em3HxiqLS0wVAMePH3IZenFOqKQOAPWLjoSwSDJrJkFjbKB
         vnvtSH+Ys1ESaUJd7g9AxxLR8gZLkVzmFs8stbt8S8DRO9YGR42ZOreazDrW1sytQyhe
         clDAJiF6GEDDzbkaafepZ5DKZV+aO5rjda93J0gd35pqU8iOV6vvnFyolq4QBQty8HR9
         qBXMzPlxMMNoSUJSpqi5FIuSRB7CWzku4BrWbmo0btWNi0QnH22oHULL6O0THJ6OnRpo
         1iVGhXFwmlWV1ACbA9TPoXebu04EtvPN5XhypDXuPO0PVY2Xz0jyfTsaiH++2aseq1T/
         N0xA==;
        dara=google.com
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of barbara.kelham@leadslitmus.com designates 188.121.53.175 as permitted sender) smtp.mailfrom=barbara.kelham@leadslitmus.com
Return-Path: <barbara.kelham@leadslitmus.com>
Received: from sxb1plsmtpa01-16.prod.sxb1.secureserver.net (sxb1plsmtpa01-16.prod.sxb1.secureserver.net. [188.121.53.175])
        by mx.google.com with ESMTPS id 41be03b00d2f7-7e6b7c90270si4881173a12.253.2024.09.25.14.04.01
        for <xxx@yyy.lol>
        (version=TLS1_2 cipher=ECDHE-ECDSA-CHACHA20-POLY1305 bits=256/256);
        Wed, 25 Sep 2024 14:04:03 -0700 (PDT)
Received-SPF: pass (google.com: domain of barbara.kelham@leadslitmus.com designates 188.121.53.175 as permitted sender) client-ip=188.121.53.175;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of barbara.kelham@leadslitmus.com designates 188.121.53.175 as permitted sender) smtp.mailfrom=barbara.kelham@leadslitmus.com
Received: from DESKTOPIQ1BCQV ([157.45.254.116])
	by :SMTPAUTH: with ESMTPSA
	id tZAqsZb8C93JetZAzs9yEk; Wed, 25 Sep 2024 14:03:58 -0700
X-CMAE-Analysis: v=2.4 cv=c8dgQg9l c=1 sm=1 tr=0 ts=66f47abf
 a=OFNxAcIpqIVXiXC3RgkKRw==:117 a=OFNxAcIpqIVXiXC3RgkKRw==:17
 a=DAwyPP_o2Byb1YXLmDAA:9 a=PdVXfRpiAAAA:8 a=-x6gYbCU0RYoce8WnX8A:9
 a=CjuIK1q_8ugA:10 a=yMhMjlubAAAA:8 a=SSmOFEACAAAA:8 a=aQEKbfMPlNBtgRf7Z9wA:9
 a=z0RuNiHixMv7XpfC:21 a=gKO2Hq4RSVkA:10 a=UiCQ7L4-1S4A:10 a=hTZeC7Yk6K0A:10
 a=frz4AuCg-hUA:10 a=zY0JdQc1-4EAyPf5TuXT:22 a=6dpdqBtIB8HXLtKMWAyx:22
X-SECURESERVER-ACCT: barbara.kelham@leadslitmus.com
From: <barbara.kelham@leadslitmus.com>
To: <xxx@yyy.lol>
References: 
In-Reply-To: 
Subject: RE: RE: JAMF Users list | Opt-in and Verified
Date: Wed, 25 Sep 2024 15:03:57 -0600
Message-ID: <!&!AAAAAAAAAAAuAAAAAAAAABuV0NyUQQdCk9Ve8hjjNwkBAMO2jhD3dRHOtM0AqgC7tuYAAAAAAA4AABAAAABPg6uoz91iTLmGKoc9b0O7AQAAAAA=@leadslitmus.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_114C_01DB0F5C.25EFEC10"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AQGTaGQVQMmubxVcic31bN1EVTP0g7L4NyMA
Content-Language: en-us
Disposition-Notification-To: <barbara.kelham@leadslitmus.com>
X-CMAE-Envelope: MS4xfJn3RHvr/XPdiLTunL6nWItJcItvLfyT9wxBk/Bv2+Ir97YV8JbxVqE6/dLgijv8U8ef3b7DeNFKoSfVrxN8WEbCxR8CoiRanfS/k6475YzDrSjCQqXu
 O4e7GpPNPrCKJ8qQfpePw/pqOHyOW4Jhpc62B2r9a4MmsnajtittWgRFrxW7/rNFXNRgAl8BFWT1wpx5RA/D0ZhMdKWEAxFJLOQ=

This is a multipart message in MIME format.

------=_NextPart_000_114C_01DB0F5C.25EFEC10
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

Hello,

 

I hope you are having a great day!

 

I am writing this email to follow up on my previous email. I haven't
received a response from you yet and I just wanted to make sure that you
have received my email. When you have a moment, could you please let me know
if you have received it or not?

 

Please acknowledge the receipt of this email.

 

Regards,

Barbara

 

 

From: barbara.kelham@leadslitmus.com <barbara.kelham@leadslitmus.com> 
Sent: Wednesday, September 4, 2024 2:09 PM
To: 'xxx@yyy.lol' <xxx@yyy.lol>
Subject: RE: JAMF Users list | Opt-in and Verified

 

Hello,

 

I haven't heard back from you yet so I just wanted to make sure you received
my previous email, when you get a moment, could you please drop me a line?

 

Please acknowledge the receipt of this email.

 

Regards,

Barbara

____________________________________________________________________________
__________

Subject: JAMF Users list | Opt-in and Verified

 

Hello,

 

I hope this message finds you well.

 

We have recently updated our JAMF Users list. Are you interested in learning
more?

 

If so, please let me know your target geography, so that we can provide you
with counts and pricing for the same.

 

Awaiting your response

 

Regards,

Barbara Kelham

Demand Generation Manager

 

To opt out, kindly reply with "no need" in the subject line.


------=_NextPart_000_114C_01DB0F5C.25EFEC10
Content-Type: text/html;
	charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" =
xmlns:o=3D"urn:schemas-microsoft-com:office:office" =
xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" =
xmlns=3D"http://www.w3.org/TR/REC-html40"><head><meta =
http-equiv=3DContent-Type content=3D"text/html; =
charset=3Dus-ascii"><meta name=3DGenerator content=3D"Microsoft Word 15 =
(filtered medium)"><style></style></head><body lang=3DEN-US =
link=3D"#0563C1" vlink=3D"#954F72" style=3D'word-wrap:break-word'><div =
class=3DWordSection1><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>Hello,<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>I hope you are having a great =
day!<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>I am writing this email to follow up on my =
previous email. I haven't received a response from you yet and I just =
wanted to make sure that you have received my email. When you have a =
moment, could you please let me know if you have received it or =
not?<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>Please acknowledge the receipt of this =
email.<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>Regards,<o:p></o:p></span></p><p =
class=3DMsoNormal style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'color:#002060'>Barbara<o:p></o:p></span></p><p =
class=3DMsoNormal><span lang=3DEN-IN><o:p>&nbsp;</o:p></span></p><p =
class=3DMsoNormal><span =
lang=3DEN-IN><o:p>&nbsp;</o:p></span></p><div><div =
style=3D'border:none;border-top:solid #E1E1E1 1.0pt;padding:3.0pt 0in =
0in 0in'><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><b>From:</b> =
barbara.kelham@leadslitmus.com &lt;barbara.kelham@leadslitmus.com&gt; =
<br><b>Sent:</b> Wednesday, September 4, 2024 2:09 PM<br><b>To:</b> =
'xxx@yyy.lol' &lt;xxx@yyy.lol&gt;<br><b>Subject:</b> RE: JAMF =
Users list | Opt-in and Verified<o:p></o:p></p></div></div><p =
class=3DMsoNormal><o:p>&nbsp;</o:p></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Hello,</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>&nbsp;</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>I haven't heard back from you yet so I just wanted to make sure you =
received my previous email, when you get a moment, could you please drop =
me a line?</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>&nbsp;</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Please acknowledge the receipt of this email.</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>&nbsp;</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Regards,</span><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Barbara<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>________________________________________________________________________=
______________<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><b><span =
lang=3DEN-IN>Subject:</span></b><span lang=3DEN-IN> JAMF Users list | =
Opt-in and Verified<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Hello,<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>I hope this message finds you well.<o:p></o:p></span></p><p =
class=3DMsoNormal style=3D'margin-bottom:0in;line-height:normal'><span =
lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>We have recently updated our <b>JAMF Users list.</b> Are you interested =
in learning more?<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>If so, please let me know your <b>target geography,</b> so that we can =
provide you with counts and pricing for the =
same.<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Awaiting your response<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Regards,<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Barbara Kelham<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'font-size:10.5pt;color:#002060;mso-ligatures:standardcontextual'=
>Demand Generation Manager<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'margin-bottom:0in;line-height:normal'><span lang=3DEN-IN =
style=3D'mso-ligatures:standardcontextual'><o:p>&nbsp;</o:p></span></p><p=
 class=3DMsoNormal style=3D'margin-bottom:0in;line-height:normal'><span =
lang=3DEN-IN =
style=3D'font-size:10.0pt;mso-ligatures:standardcontextual'>To opt out, =
kindly reply with &quot;no need&quot; in the subject =
line.<o:p></o:p></span></p></div></body></html>
------=_NextPart_000_114C_01DB0F5C.25EFEC10--

**Comment by TechArea** [comment]
All FQDNs that do not prevent mails from being sent in their name should be blocked per se.
Where will we end up if the technical security functions are simply not used or ignored?
Well, it will just end up on my personal block list.
It's incomprehensible that negligent operators are simply not sanctioned.
Let me say it clearly: it sucks

**Comment by spirillen** [comment]
> All FQDNs that do not prevent mails from being sent in their name should be blocked per se.

Their are by the SPF record.

In this case you should start by looking at the SPF record, in this case this allows `"v=spf1 include:secureserver.net -all"`, so the "anti" spam rules are in order, according to the RFC.

> Well, it will just end up on my personal block list.

Wont help you at all, you'll have to add `secureserver.net` to your blacklist, for it to help, but that will then also be helping you a lot, as 99.9999% of all mails from their servers are pure spam.


> Let me say it clearly: it sucks

It sure does. 😃
