### ISSUE TITLE
freeanimesonline.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#1232]
### Comments

There is barely containing any trackers. Please add these.
Original post in https://github.com/mypdns/matrix/issues/1220

Credit: @houmie

### Wildcard domain records

```CSV
freeanimesonline.com|torrent
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
null
```

### SeafeSearch records

```CSV
null
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/06f2907f-2d2f-40a1-80e1-d3434d310172)

</details>

### Links to external sources

```CSS
https://www.vpnmentor.com/blog/10-best-torrent-websites/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
@ShadowWhisperer, you are missing this one in your tunnel list

As we do not maintain any proxylist I'll recommend you to use @ShadowWhisperer Tunnels list

**Comment by ShadowWhisperer** [comment]
Added to 'Tunnels'.

Thanks!
