### ISSUE TITLE
yotpo.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1336]
### Comments

Subdomain used in long term Meta Mask phishing campaign.

### Wildcard domain records

```CSV
yotpo.com|adware,phishing,redirector,spam,tracking
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```css
ads.yotpo.com|adware
b2b.yotpo.com|adware
destination.yotpo.com|tracking,redirector
em.yotpo.com|tracking,redirector,phishing
events.yotpo.com|tracking
gfeed.yotpo.com|tracking
metrics.yotpo.com|tracking
p.yotpo.com|tracking
salesloft.yotpo.com
smsbump.yotpo.com
staticw2.yotpo.com|tracking
w2.yotpo.com|tracking
widget.yotpo.com
www.yotpo.com
```

### Screenshots

<details><summary>Screenshot</summary>

![Screenshot 2024-11-21 174636](https://github.com/user-attachments/assets/2a7caa12-2d87-4042-8c87-9a4bdc20489c)

![Screenshot 2024-11-21 175037](https://github.com/user-attachments/assets/3d15f60e-deb0-485a-8d94-f21723daf237)

![image](https://github.com/user-attachments/assets/4d02c6c0-0406-4d80-812a-1f17f41e4a5c)

</details>

### Links to external sources

```CSS
https://urlscan.io/result/52284e24-388a-4d59-a08e-c643881aa5bb/
https://www.virustotal.com/gui/url/a4bb23d70ee59646068216dd25a1670d5384092233996208129ace595d2ca459
https://app.any.run/tasks/a16fe9a1-a656-4266-91ec-5c2782c6b3f9
https://www.reddit.com/r/BinanceUS/comments/1awq4zx/believe_i_got_a_phishing_scam_regarding_metamask/
https://www.tokentrace.com/post/metamask-phishing-email-protect-your-crypto-assets
https://any.run/report/2131d0f2b16f534275a7150f49ff750ec92c695ecd5e2c88189a48ea4e653710/72484f09-bcde-4dd6-806b-5386c194e4ed
https://any.run/report/886659a97808099c0e2566cc0c63f814d5709283804953ce14f538c145c18adc/53ebc68d-e763-4749-82bb-ce31e591ba45
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Found a lot more categories to this domain, updating and ads to index
