### ISSUE TITLE
com-trackanie.top

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1638]
### Comments

Domain being used for USPS delivery failure lures. See also: https://github.com/Phishing-Database/phishing/pull/548

### Wildcard domain records

```CSV
com-trackanie.top|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![847367a1-2498-4aa4-a58f-27db64a22d1e](https://github.com/user-attachments/assets/fc0f7ba5-e4ef-407c-b28f-4c0c6e7cf42f)

</details>

### Links to external sources

```CSS
https://usps.com-trackanie.top/us/ 
https://urlscan.io/result/847367a1-2498-4aa4-a58f-27db64a22d1e/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Just to be sure, is this one `om-trackanie.top` _OR_ `com-trackanie.top`?

**Comment by g0d33p3rsec** [comment]
com, good catch.
