### ISSUE TITLE
bqizimv.ru

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1717]
### Comments

When following up on https://github.com/Phishing-Database/Phishing.Database/issues/949 I discovered this domain phishing for Microsoft credentials.

### Wildcard domain records

```CSV
bqizimv.ru|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![211809b9-58a0-4d3f-a523-55975bb2918d](https://github.com/user-attachments/assets/c88cd7a7-4226-41cf-b3df-2283f5cecdf3)

</details>

### Links to external sources

```text
https://uz.bqizimv.ru/O8SI/
https://app.any.run/tasks/010a5d81-928d-4e10-aacd-83915a91405f
https://urlscan.io/result/462c36b4-62cb-4d75-9555-72317d779745/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Domain are not assigned any IP address, yet I'm adding this one as potential dangerous.

**Comment by g0d33p3rsec** [comment]
> Domain are not assigned any IP address, yet I'm adding this one as potential dangerous.

check the uz subdomain
```
;; QUESTION SECTION:
;uz.bqizimv.ru.                 IN      A

;; ANSWER SECTION:
uz.bqizimv.ru.          300     IN      A       104.21.56.64
uz.bqizimv.ru.          300     IN      A       172.67.178.202
```

**Comment by g0d33p3rsec** [comment]
Infoblox released a pretty good deep dive on this sort of garbage last July -- [REGISTERED DGAs: The Prolific New Menace No One Is Talking About](https://insights.infoblox.com/resources-research-report/infoblox-research-report-registered-dgas-the-prolific-new-menace-no-one-is-talking-about).
![image](https://github.com/user-attachments/assets/69b81eb8-0cf2-4f59-8290-bb99f5290ed4)

**Comment by spirillen** [comment]
> > Domain are not assigned any IP address, yet I'm adding this one as potential dangerous.
> 
> check the uz subdomain

Interesting operation...

**Comment by spirillen** [comment]
added in https://github.com/mypdns/matrix/commit/67bb121088bc59d14b716a2f15e70bc183e82119
