### ISSUE TITLE
lpadc.asia

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1718]
### Comments

I saw a fediverse post advising people to beware of USPS, UPS, and FedEx smishing campaigns timed to coincide with Christmas. The post contained the shortened link `https://bit.ly/49XzyQk?OFQ=3nQv5A1zB5` which `bit.ly` has flagged as potentially malicious. That link contained a second shortened link `https://t.co/2Klve5f1Dg` which finally redirected to `https://lpadc.asia/hmy7p33n/`, containing a USPS delivery failure lure. The page is protected by CloudFlare and seems to be checking for the previous source in the referrer header, as attempting to scan the specific URIs fails.  See also: https://github.com/Phishing-Database/phishing/pull/554

### Wildcard domain records

```CSV
lpadc.asia|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![Screenshot 2024-12-26 152025](https://github.com/user-attachments/assets/214d2b01-657f-406b-be23-773596207da7)
![fc16640f-ab30-4fbd-9c7a-02576cf0b59b](https://github.com/user-attachments/assets/8fbc29e9-62e6-477e-87a0-f83235056f42)
![Screenshot 2024-12-26 152144](https://github.com/user-attachments/assets/bfcf4db2-52fd-4816-a552-ccd44f84c333)
![666ae707-6454-4508-96ff-009424ffd716](https://github.com/user-attachments/assets/930449e8-5ec7-4958-9f45-d8978deba91b)

</details>

### Links to external sources

```text
https://lpadc.asia/hmy7p33n/
https://bit.ly/49XzyQk?OFQ=3nQv5A1zB5
https://bird.makeup/users/litmoose/statuses/1871663497366655182
https://urlscan.io/result/fc16640f-ab30-4fbd-9c7a-02576cf0b59b/
https://urlscan.io/result/666ae707-6454-4508-96ff-009424ffd716/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
> The page is protected by CloudFlare and seems to be checking for the previous source in the referrer header

WOW that is advanced, and it for sure makes it harder to detect these lures, this means any scrapers know have to follow a link and keep the headers. That sucks dude, but somehow not unexpected, there are money involved.

**Comment by g0d33p3rsec** [comment]
> > The page is protected by CloudFlare and seems to be checking for the previous source in the referrer header
> 
> WOW that is advanced, and it for sure makes it harder to detect these lures, this means any scrapers know have to follow a link and keep the headers. That sucks dude, but somehow not unexpected, there are money involved.


Between the antiforensics of the traffic distribution systems and the algorithmically generated and registered domain names, the future is looking... interesting.


> And just why `t.co` are still marked for phishing... `https://t.co/2Klve5f1Dg` [MTX-575](https://kb.mypdns.org/issue/MTX-575) | #470 are not marked in any way

There are more bots than humans on twitter now anyway.

**Comment by spirillen** [comment]
> There are more bots than humans on twitter now anyway.

Hmm... interesting, where have you obtained that info?

**Comment by g0d33p3rsec** [comment]
> Hmm... interesting, where have you obtained that info?

passive observation from an account that went from 900 to 1200 followers just before the election (all bots) and back to 800 after the remaining humans that followed my account left following.  Oddly, they still seem to be more proactive about removing malicious content than Facebook or Alphabet.
