### ISSUE TITLE
edumnhn.weebly.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1719]
### Comments

While investigating https://github.com/Phishing-Database/Phishing.Database/issues/970 I noticed multiple sites that were using `beacons.ai` were also using `webwave.dev` as a part of their attack chain.  More information is available at: https://github.com/Phishing-Database/phishing/pull/558

This particular page seems to be targeting `https://www.mnhn.fr/fr`

### Wildcard domain records

```CSV
edumnhn.weebly.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![c6ce0ffd-ecc6-4507-abe3-6b7b3f577558](https://github.com/user-attachments/assets/6c492a16-9a52-40dd-a2eb-6bd5c3bd3195)

</details>

### Links to external sources

```text
https://edumnhn.weebly.com/
https://urlscan.io/result/c6ce0ffd-ecc6-4507-abe3-6b7b3f577558/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Moved to MTX-639 (https://kb.mypdns.org/issue/MTX-639) https://github.com/mypdns/matrix/issues/638
