### ISSUE TITLE
wixsite.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#1721]
### Comments

While investigating https://github.com/Phishing-Database/Phishing.Database/issues/970 I noticed multiple sites that were using `beacons.ai` were also using `webwave.dev` as a part of their attack chain.  More information is available at: https://github.com/Phishing-Database/phishing/pull/558

### Wildcard domain records

```CSV
gevra908.wixsite.com|phishing
jeanhoudayersa.wixsite.com|phishing
mepepoj711.wixsite.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![7cf1f944-f806-4eb3-9aa2-e3fc087660a8](https://github.com/user-attachments/assets/3c2f7a53-1a52-402d-a65e-af6cffeb2d93)

</details>

### Links to external sources

```text
https://gevra908.wixsite.com/my-site-1 
https://urlscan.io/result/7cf1f944-f806-4eb3-9aa2-e3fc087660a8/
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
All credit to @g0d33p3rsec 

-------

### Comments

While investigating https://github.com/Phishing-Database/Phishing.Database/issues/970 I noticed multiple sites that were using `beacons.ai` were also using `webwave.dev` as a part of their attack chain.  More information is available at: https://github.com/Phishing-Database/phishing/pull/558

### Wildcard domain records

```CSV
jeanhoudayersa.wixsite.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![ff7078d8-6065-4ff4-8843-cee1f25f3cf1](https://github.com/user-attachments/assets/770f1425-fb0c-4576-99b0-72fa8a52a944)

</details>


### Links to external sources

```text
https://byan.at/KZqn6
https://jeanhoudayersa.wixsite.com/my-site-2
https://urlscan.io/result/ff7078d8-6065-4ff4-8843-cee1f25f3cf1/
```

**Comment by spirillen** [comment]
All credit to @g0d33p3rsec 

-------

### Comments

While investigating https://github.com/Phishing-Database/Phishing.Database/issues/970 I noticed multiple sites that were using `beacons.ai` were also using `webwave.dev` as a part of their attack chain.  More information is available at: https://github.com/Phishing-Database/phishing/pull/558

### Wildcard domain records

```CSV
mepepoj711.wixsite.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![fe42dd78-75b1-4d17-a41e-d129e461e3fe](https://github.com/user-attachments/assets/f6fda092-0c53-4960-9cba-f4676061b83e)

</details>


### Links to external sources

```text
https://mepepoj711.wixsite.com/my-site-2
https://urlscan.io/result/fe42dd78-75b1-4d17-a41e-d129e461e3fe/
```
