### ISSUE TITLE
bnc.lt

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#31]
## Summary

This domain is used for 'Tracking' your private life and **HAVE** to be 
blocked as..

- [ ] [Single Domain](source/tracking/domains.list)
- [X] [Wild carded](source/tracking/wildcard.list)

```python
bnc.lt   CNAME . ; Tracking
*.bnc.lt   CNAME . ; Tracking
```

... ***because***:

## Relevant logs and/or screenshots

> Increase mobile revenue with enterprise-grade links built to acquire, engage, and measure across all devices, channels, and platforms.

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/44526987/72208668-b50d0900-34a5-11ea-8cba-b4507d0d7cbc.png)

</details>

## RPZ history

```
bnc.lt.rpz.mypdns.cloud
custom.bnc.lt.rpz.mypdns.cloud
dev.bnc.lt.rpz.mypdns.cloud
epsilon.thirdparty.bnc.lt.rpz.mypdns.cloud
thirdparty.bnc.lt.rpz.mypdns.cloud
www.bnc.lt.rpz.mypdns.cloud
```

These will be coocked down to wildcard

### All Submissions:
- [X] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [X] Added ScreenDump for prove of False Positive
- [X] Have you added an explanation of what your submission do and why
	you'd like us to include them??

### Testing face
- [X] Checked the internet for verification?
- [X] Have you successfully ran tests with your changes locally?

### Todo:
- [x] RPZ Server (Team members)
- [x] Added to Source file

**Comment by AnonymousPoster** [comment]
https://github.com/mypdns/matrix/commit/c390dd84bf1713664ca59bb55dfef9a97d966dd3
