### ISSUE TITLE
Login issues on https://mypdns.org/

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#417]
# Login Issues

In case you experience any login issues on [https://mypdns.org/](https://mypdns.org/), please post any comments and share notes experience here. The reason is, that installing Gitlab code and configure it is something I started on Fri, 18th June 2020, so please bare with some beginner issues.

PS: I know the incoming mail isn't working, that's probably a firewall issue, and there are troubles sending e-mails to hetzner.de, @funilrys have opened and issue with them to try solving the problem.

**Comment by funilrys** [comment]
Shouldn't this be a discussion ?

**Comment by spirillen** [comment]
??

**Comment by spirillen** [comment]
> Shouldn't this be a discussion ?

:thinking: 
What makes you believe this should be moved to a discussion??

**Comment by funilrys** [comment]
Kurzschuss Reaktion.

**Comment by spirillen** [comment]
> Kurzschuss 

Thanks good for my old red translation dictionary :smirk: yep, the old red one from the 80's.

That said, have had time to get in touch with Hetzner about why you can't receive mails from mypdns?
