### ISSUE TITLE
Chinese spyware domain update request

### ISSUE THREAD

**Issue by c2xusnpq6** [mypdns/matrix#418]
https://github.com/mypdns/matrix/blob/73c29653317009f9ad4fa19e0f50e5f52f92d549/source/spyware/domains.list#L6
https://github.com/mypdns/matrix/blob/73c29653317009f9ad4fa19e0f50e5f52f92d549/source/spyware/domains.list#L13

Same owner's domain:
![image](https://user-images.githubusercontent.com/75058881/126159856-36dacf42-43be-4cb3-97f1-a15d2f44194c.png)

![image](https://user-images.githubusercontent.com/75058881/126159894-cd0a2deb-6b20-4c20-b94c-911b907296f6.png)

(I only use GitHub, sorry ^^'')

**Comment by spirillen** [comment]
All issues have to bee posted at [mypdns,org](https://mypdns.org/my-privacy-dns/matrix) do to the [Anti Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement) by Github, Sorry, but no support here at all

**Comment by c2xusnpq6** [comment]
I am not requesting deletion, but requesting addition...😅😅😌

**Comment by spirillen** [comment]
Still, there is no why...  I know you have added some screenshots, unfortunately I didn't had Chineese in the school, only english and german :smirk:
