### ISSUE TITLE
Update of `pwt.soundcloud.com`

### ISSUE THREAD

**Issue by D4v1dH03** [mypdns/matrix#420]
I am sorry but I recently browsed the issues of Easylist
And a person who work at Soundcloud mentioned in the following issue:
https://github.com/easylist/easylist/issues/10173

That the `pwt.soundcloud.com` domain is NOT for tracking but only to identify bot abuse.

And I cannot file an issue at the MyPDNS GitLab instance because my account is "pending approval and blocked"

Would you please take a look at it?

I apologise again.

**Comment by spirillen** [comment]
Your account should be active.  And there is certainly something I have to look at, as there should not be any approval setup...

**Comment by spirillen** [comment]
I think I found the problem in the config... Let's cross our fingers :crossed_fingers:

**Comment by D4v1dH03** [comment]
> Your account should be active. And there is certainly something I have to look at, as there should not be any approval setup...
> 
> Please add your comment to https://mypdns.org/my-privacy-dns/matrix/-/issues/3888

Comment added on there.

**Comment by spirillen** [comment]
Should be solved with the following commits

- https://mypdns.org/my-privacy-dns/matrix/-/commit/ff4849a5c31f0fe22222f2c953f2730f1c46d9db
- https://mypdns.org/my-privacy-dns/matrix/-/commit/72d707fd3922ba403c57e0add6e368977fda61f3
- https://mypdns.org/my-privacy-dns/matrix/-/commit/ae7e024b3b86e17051e05a975fda9276a65299b5
