### ISSUE TITLE
mypdns.org is down

### ISSUE THREAD

**Issue by s1gmus** [mypdns/matrix#424]
and all template issues { https://github.com/mypdns/matrix/issues } are pointing to mypdns.org links which all of them are dead.

**Comment by spirillen** [comment]
From the chat at [anontier.nl](https://matrix.to/#/!oDJVRKtqiXOByBPJrB:anontier.nl?via=anontier.nl&via=matrix.org&via=trygve.me)

![image](https://user-images.githubusercontent.com/44526987/172639936-0495a869-2bba-4926-b92a-198145e29ad8.png)

For the issue templates, then yes, as There no longer are any trust in Github serving our projects do to the countless times they have been disabling out projects.

The project is not dead, I'm trying to recover from my economic situation, which might yet take some time, unless as mentioned in the screenshot, it starts raining with support (money).

**Comment by spirillen** [comment]
AS the setup is rather stable by no, I'm closing this issue
