### ISSUE TITLE
[Add request] List of suggestions for sources of hosts data Gambling

### ISSUE THREAD

**Issue by alsyundawy** [mypdns/matrix#443]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [X] Subdomain, We should not blacklist the entire domain, only sub-domains
- [X] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Domain records

Which domain(s) should be blocked?

List of suggestions for sources of hosts data Gambling (Indonesia)

https://github.com/alsyundawy/TrustPositif/raw/main/gambling_indonesia.txt

Why should these domain(s) be blocked?
indonesia gambling site

**Comment by spirillen** [comment]
Closed for inactivity
