### ISSUE TITLE
ajstelecom.com.mx

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#450]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments
- An abuse report has been filed with Newfold Digital.  Recent reports have typically been addressed within 24 hours. (March 18, 2024) 

### Domain records

```CSV
ajstelecom.com.mx|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![b370d0cb-e11f-4025-9689-7b0ce90aa96c](https://github.com/mypdns/matrix/assets/108126637/d786e087-ef06-40af-8664-5a59e4257878)
![e2705202-9baa-4df5-8265-482c1527fe9f](https://github.com/mypdns/matrix/assets/108126637/35a69950-f710-4a33-9c0a-3fffe2ea450d)
![a2624d51-689f-4940-8360-77e82ce68d23](https://github.com/mypdns/matrix/assets/108126637/b05f0eed-097e-4a0a-a507-49fceec662d6)
![5f69456f-dc43-407d-aab5-837c36d9dd38](https://github.com/mypdns/matrix/assets/108126637/e59221f3-695e-47b0-867f-06c7c278e16c)
![b2b1c2ff-3ce1-4e2d-b381-4dbf88b07380](https://github.com/mypdns/matrix/assets/108126637/1ec74007-cb7d-4d11-b081-e85bdb2a8dd5)
![image](https://github.com/mypdns/matrix/assets/108126637/12c837b7-f2c8-41ed-b59b-aa024eaa7b18)
![c7c8287f-e63d-43a1-9921-5c275c0f8689](https://github.com/mypdns/matrix/assets/108126637/672fda3e-701a-4405-9021-985d69d8a062)
![e6a6de31-90e7-4100-9207-2f0e82ae0ebc](https://github.com/mypdns/matrix/assets/108126637/e45932d7-c827-43bb-b766-1711da43ae34)
![10a9c663-86ed-4295-8d46-240cb70b8da6](https://github.com/mypdns/matrix/assets/108126637/77f1c7c3-2431-4d88-a1ad-02e6c5b03cb6)
![screenshot](https://github.com/mypdns/matrix/assets/108126637/82a12985-f0f5-4a8f-bf31-5d0d76a576af)
![image](https://github.com/mypdns/matrix/assets/108126637/333e85fd-446a-4359-82d9-0d1b7a9f0fa8)
![screenshot](https://github.com/mypdns/matrix/assets/108126637/ce7d14f1-fa7d-417c-92ad-15ba61bc346d)
![image](https://github.com/mypdns/matrix/assets/108126637/f4241881-4712-4063-a10c-1b71d13c54da)
![a465d9ec-6a55-44c0-be8a-c9fd54fd4234](https://github.com/mypdns/matrix/assets/108126637/0b356033-dfb1-4fad-b309-fa202311e1bb)
![08ab6a33-d687-46a5-ac63-ac2970127622](https://github.com/mypdns/matrix/assets/108126637/556f0b63-e165-4a86-a734-30121c618484)
![image](https://github.com/mypdns/matrix/assets/108126637/e8fca9c1-47da-49f0-809c-17b094795fae)
![image](https://github.com/mypdns/matrix/assets/108126637/684aa838-037a-4ccc-baee-f5cbc05bd003)
![screenshot](https://github.com/mypdns/matrix/assets/108126637/6f8b4459-2bd4-486c-a7e7-38c26eaabb2f)
![image](https://github.com/mypdns/matrix/assets/108126637/e561a0ac-3277-468e-91d1-287022e1c915)
![screenshot](https://github.com/mypdns/matrix/assets/108126637/889f4da7-af56-42bb-9c5e-085706194956)
![d4a4c99a-6012-4f40-97c3-6719b988a618](https://github.com/mypdns/matrix/assets/108126637/ccf7c21d-35c1-4b2b-aac7-035b059c58d6)
![bebd23a5-6e16-4a21-8367-4ae77b1408c2](https://github.com/mypdns/matrix/assets/108126637/416b9f0a-ecd0-4574-91f2-56f806b237c2)
![7f2f7832-4af4-4c45-9f3f-24622ebbc416](https://github.com/mypdns/matrix/assets/108126637/e971c43a-7471-485b-84d1-37458cede194)
![36e1c529-1c43-4e88-a382-e3afc4648f76](https://github.com/mypdns/matrix/assets/108126637/3dd649ce-1a83-4e3c-8e72-b64d4599cdfe)
![727ddb11-5299-4501-b3b3-277fce1feb36](https://github.com/mypdns/matrix/assets/108126637/cc1a5019-7ca9-4129-abbe-bdeb09dd8d84)
![84ec271c-be1f-4a77-bff4-200390cb4624](https://github.com/mypdns/matrix/assets/108126637/8f4064a4-2adf-4051-a558-0cc1dd714470)
![image](https://github.com/mypdns/matrix/assets/108126637/851361d8-a408-4b33-89cf-fe76694dfceb)

</details>

### Links to external sources

```
https://ajstelecom.com.mx/M1YyMjRKOXEwdDczNFo= 
https://urlscan.io/result/b370d0cb-e11f-4025-9689-7b0ce90aa96c/
https://ajstelecom.com.mx/M1UyRjBFNkg3WTV2MHM=
https://urlscan.io/result/e2705202-9baa-4df5-8265-482c1527fe9f/
https://ajstelecom.com.mx/M0cyYzVtMUgyNDJaMGw=
https://urlscan.io/result/a2624d51-689f-4940-8360-77e82ce68d23/
https://ajstelecom.com.mx/M04yeDVwMHg2QTRuM1Q=
https://urlscan.io/result/5f69456f-dc43-407d-aab5-837c36d9dd38/
https://ajstelecom.com.mx/M3gyTzVGMlYxRjBON2U=
https://urlscan.io/result/b2b1c2ff-3ce1-4e2d-b381-4dbf88b07380/
https://ajstelecom.com.mx/M1MyMTVvMTA4YjhoNnE=
https://urlscan.io/result/961d509f-61cd-4a13-91ef-6e3f2b42fa61/
https://ajstelecom.com.mx/M3YyODVqMWw4VjgzNkg=
https://urlscan.io/result/32a36ae2-29d1-47c9-a32e-22c370f2f3ef/
https://ajstelecom.com.mx/M1YwTDk5MkgxZzE1MXY=
https://urlscan.io/result/c7c8287f-e63d-43a1-9921-5c275c0f8689/
https://ajstelecom.com.mx/M0syMjVqMWI5NDl4N0I=
https://urlscan.io/result/e6a6de31-90e7-4100-9207-2f0e82ae0ebc/
https://ajstelecom.com.mx/M0kybDVGMUk3UzJrNDM
https://urlscan.io/result/10a9c663-86ed-4295-8d46-240cb70b8da6/
https://ajstelecom.com.mx/M1AySjRCODM1czBnNUU=
https://urlscan.io/result/9e9d0a7d-6651-49b5-8721-69e472f6fe02/
https://radar.cloudflare.com/scan/b06fa80b-cc53-4ce7-92b1-548eebb08bb0/
https://ajstelecom.com.mx/Mnc5MzF0MFI5WjhFNFI= 
https://urlscan.io/result/e06609b1-8abd-4393-890c-c420405b526f/
https://radar.cloudflare.com/scan/61c40842-fedc-4c5e-8fd3-d387dc4be0a9/
https://ajstelecom.com.mx/M2wxRjNYMmgwVDJ1MXo=
https://urlscan.io/result/aa1fde3f-4eff-4f10-950c-8663f4f4fcdb/
https://radar.cloudflare.com/scan/b55dc186-a9e1-4417-b1e0-e414e8219f2c/
https://ajstelecom.com.mx/M20yUjU0MXU0TzRYNWc=
https://urlscan.io/result/002b4d81-700c-4954-bfda-82492bec23c1/
https://ajstelecom.com.mx/Mm04YTJpOHU0STloNHQ=
https://urlscan.io/result/a465d9ec-6a55-44c0-be8a-c9fd54fd4234/
https://ajstelecom.com.mx/Mks5QjhONXEyMjcyMmE= 
https://urlscan.io/result/08ab6a33-d687-46a5-ac63-ac2970127622/
https://ajstelecom.com.mx/M00ybzI2NG83YjdpNDg=
https://urlscan.io/result/8c8c3821-67e3-4639-a120-ef5507adefd4/
https://ajstelecom.com.mx/M0cwTDNGOXMxZzBWMGY=
https://urlscan.io/result/57c21fce-628b-4e5d-8abe-e354ea0ea9f1/
https://ajstelecom.com.mx/MzIyMDV6MkE3ODFxMzg=
https://urlscan.io/result/2d7cb5d8-796e-4a35-a03a-e3a129889341/
https://radar.cloudflare.com/scan/cc3fe5ea-3c4c-47e6-9fd6-073e700035e5/
https://ajstelecom.com.mx/M3EyYTR6Nkw3djdaM0Y=
https://urlscan.io/result/2d85beb5-8e17-423f-abfe-0dc37a22f7c8/
https://ajstelecom.com.mx/M1gyRDVBMHI0TjQyMVQ=
https://urlscan.io/result/11ec8ec5-c9ed-43d1-b3f4-586d17dd56ae/
https://radar.cloudflare.com/scan/8e3255a7-1ffd-437a-abe8-3448366ed537/
https://ajstelecom.com.mx/M3AyazVkMlAzbTdHNW0=
https://urlscan.io/result/82ab0c44-bfe9-4a0c-9080-c48a58b4a571/
https://radar.cloudflare.com/scan/db22404c-6571-4a3c-9e28-525443681dd1/
https://ajstelecom.com.mx/MzgyQTRuMzU0ODBtNG4=
https://urlscan.io/result/d4a4c99a-6012-4f40-97c3-6719b988a618/
https://ajstelecom.com.mx/MnA0OThTMzA1RTRpN2w=
https://urlscan.io/result/bebd23a5-6e16-4a21-8367-4ae77b1408c2/
https://ajstelecom.com.mx/M3gxRTIxODkxdzFLNmQ=
https://urlscan.io/result/7f2f7832-4af4-4c45-9f3f-24622ebbc416/
https://ajstelecom.com.mx/M04xNjJOMkQzbzk2NUs= 
https://urlscan.io/result/36e1c529-1c43-4e88-a382-e3afc4648f76/
https://ajstelecom.com.mx/MzcydzE3N0IyNDVnOFQ= 
https://urlscan.io/result/727ddb11-5299-4501-b3b3-277fce1feb36/
https://ajstelecom.com.mx/M0wxVDJIMFc0ZDBNMzQ=
https://urlscan.io/result/84ec271c-be1f-4a77-bff4-200390cb4624/
https://ajstelecom.com.mx/M3kxazd6NEcwZjBaNHI=
https://urlscan.io/result/46b04855-4243-4d42-93c4-76f6f3d14df0/
```

**Comment by spirillen** [comment]
Wow, that looks great, only one little mistake(typo) in your template...

```
### logs from [uBlock Origin](https://github.com/gorhill/uBlock/)
```

Is a H3 Header, not part of the code base area

And your `_No response_` is spot on, as that is designed to find cross refs between domains to spot new adware and trackers + porn CDN's.

----------

I#m missing a comment field, in this issue template, Let me add it right up.

**Comment by spirillen** [comment]
I believe the updated template should be in order. If you find any thing with it, please comment.

PS, rather than adding all of this to and uri `hxxps://ajstelecom[.]com[.]` you can just surround the text with 3 backticks like this

```
https://ajstelecom.com.
```

Then if you comes to a point where you need to visit the link, you save your self a lot of work, and the back ticks ensures the link, will be handled like code, and the link will remain inactive

**Comment by g0d33p3rsec** [comment]
Sounds good, thank you for the feedback.  I replaced the defanged URLs with proper links.  I went ahead and manually inserted a comment.
