### ISSUE TITLE
Adult sites

### ISSUE THREAD

**Issue by adsdestroyer** [mypdns/matrix#451]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
adult , porn, indian sex, porn videos
```

### Domain records

```CSV
mmsbee24.com|adult
mmsmasala.com|adult
uncutmaza.cc|adult
fry99.com|adult
bee121.com|adult
aagmaal.pm|adult
ixiporn.org|adult
```

### Screenshots

<details><summary>Screenshot</summary>

</details>

### Links to external sources

```CSS
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Thanks for your contribution @adsdestroyer 

`fry99.com` moved to `bee121.com`
