### ISSUE TITLE
littleswanaircon.com.sg

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#462]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
This site is now hosting the kit that was previously at iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, and ajstelecom[.]com[.]mx
```

### Domain records

```CSV
littleswanaircon.com.sg|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![Screenshot 2024-04-07 181940](https://github.com/mypdns/matrix/assets/108126637/45e85743-8a5d-4e0b-bb06-a0affc26c82b)
![Screenshot 2024-04-07 182056](https://github.com/mypdns/matrix/assets/108126637/cf7f906d-5012-4f8c-927d-5246ab7d5ca9)
![Screenshot 2024-04-07 182156](https://github.com/mypdns/matrix/assets/108126637/e4af942c-b777-4aa0-8d32-e9aed888ec95)
![Screenshot 2024-04-07 182210](https://github.com/mypdns/matrix/assets/108126637/ea399b7f-7a5f-47e4-a906-f4d7fb7862e6)
![Screenshot 2024-04-07 182224](https://github.com/mypdns/matrix/assets/108126637/602e6542-a050-4955-8b90-3e972e5aa1e7)
![Screenshot 2024-04-07 182242](https://github.com/mypdns/matrix/assets/108126637/4025c2c7-a4aa-4221-bf6d-9921fc672369)
![320326946-e984a351-1200-4bd6-ab00-4d1dd139ece9](https://github.com/mypdns/matrix/assets/108126637/e89d90b4-32fd-48dd-84c4-846c8cc22950)
![320326969-eb3e3ca7-4e79-4a55-845a-b7d469d8c174](https://github.com/mypdns/matrix/assets/108126637/c7a46c16-cbdc-4b3b-8874-2b91029ece96)
![320326987-1fea8dec-5c14-46b9-959b-1e64a0b2bdae](https://github.com/mypdns/matrix/assets/108126637/8a4a94a0-4b6f-4f14-a16d-8863608c0ddd)
![320327207-3e41faeb-69e8-4f40-9af9-fa38ae75efbd](https://github.com/mypdns/matrix/assets/108126637/eed81cdf-2e88-430f-899d-95c1fb964455)
![320330718-a2038b4b-2c8b-4335-9abd-6a6f15d40837](https://github.com/mypdns/matrix/assets/108126637/c3a91de2-ee04-4dd9-8acb-2efe48904aef)
![320330983-372de8bd-6669-4687-a79e-ce9adce828fc](https://github.com/mypdns/matrix/assets/108126637/36a48fd3-566e-4bc0-875a-415266b1a1f3)

</details>

### Links to external sources

```CSS
https://littleswanaircon.com.sg/M3kxNjlONDc3cDI4N1c=
https://littleswanaircon.com.sg/M2cyTThJNjU2TDZyN2Y=
https://littleswanaircon.com.sg/MzgyRTh4Nmw5ZDVhOUk=
https://littleswanaircon.com.sg/M2UxZjNtMGc1RDM2NTI=
https://littleswanaircon.com.sg/MzAyRDg4OFExUzFSMXQ=
https://littleswanaircon.com.sg/M2cxNTcxMk42czlUMjE=
https://littleswanaircon.com.sg/M1YxVzN1MjIwcDJiMWE=
https://littleswanaircon.com.sg/M1oycDcyOWk4TTFTN1E=
https://littleswanaircon.com.sg/M0kyVTdPNjcxdjVwNzY=
https://littleswanaircon.com.sg/M2MyRTZGNFQ3ZzhONk8=
https://littleswanaircon.com.sg/M1UySTZnOHMyaTBGOU0=
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Super, thanks for reporting :wave:
