### ISSUE TITLE
westernautomobileassembly.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#463]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
This site is now hosting the kit that was previously at littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, and ajstelecom[.]com[.]mx
```

### Domain records

```CSV
westernautomobileassembly.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/mypdns/matrix/assets/108126637/eb6afc1f-c11d-49ee-b1d1-c25aec0b1576)
![image](https://github.com/mypdns/matrix/assets/108126637/663873f9-4f02-42b5-b236-17e54e3c241f)
![322489730-2bf85e59-c723-47b0-ac4c-05bb73a200d1](https://github.com/mypdns/matrix/assets/108126637/9dcdbea3-e584-4d1a-8387-3a96945afede)
![322543812-a9b29b94-6c70-4310-a5c8-35bc221a2a3e](https://github.com/mypdns/matrix/assets/108126637/1173c738-0b48-44fe-a42f-be6cf41b493f)
![322632101-4e419d09-c9da-44c9-9e47-307de7aa9000](https://github.com/mypdns/matrix/assets/108126637/e433137d-6bc5-49b2-a348-ddc1e9b39f3f)
![322632444-2f5bba70-2106-4716-8418-75d66315c6da](https://github.com/mypdns/matrix/assets/108126637/8e5630e8-922d-4a91-b6c9-22ff343f480e)
![322632522-15f09dda-46f2-4ea3-9289-49d209a02e3e](https://github.com/mypdns/matrix/assets/108126637/d4f847aa-4928-4290-9bfd-745a306bb721)
![322632618-7d411c54-e62e-4c60-b429-c9120dbf5ee1](https://github.com/mypdns/matrix/assets/108126637/e9f6476e-3ec4-414d-9caa-22954f4b55c2)
![322632851-d762a731-68b4-47d6-81c0-b0e605483e56](https://github.com/mypdns/matrix/assets/108126637/0e733563-73d7-4ffd-a305-5b7b1144ad27)
![322654456-8f1b8937-23b4-4416-9fb4-a62a29f2dc27](https://github.com/mypdns/matrix/assets/108126637/00ad9f10-e521-4e95-8f72-b0e97b91ef45)
![322654491-205c2709-fcdb-4ca2-b1e0-9cd3d0a41375](https://github.com/mypdns/matrix/assets/108126637/e75c409d-e03c-4891-ba0b-48d357c3fcfa)
![322661443-84bb7788-bc83-41c0-a8af-0c76ac44ac2c](https://github.com/mypdns/matrix/assets/108126637/932a6197-21c1-4f7f-bdcd-3f2db63c44ef)
![322816886-972bf30e-879f-454f-9c9b-9f1e24e347d2](https://github.com/mypdns/matrix/assets/108126637/d8a74e20-7aa4-4f61-8f67-beb92447bbd1)
![322816954-728686bc-457a-411a-97cb-2ce80952d755](https://github.com/mypdns/matrix/assets/108126637/68c3905e-58f5-4148-b1ff-9e6274c85748)
![322817016-f5653b8f-2e65-40e9-aeca-133f5dd1a7a7](https://github.com/mypdns/matrix/assets/108126637/6ed4fa47-da6c-4efc-80be-85b191d3969e)
![322817104-4ed077fd-d536-4c03-a75f-a5e85c216561](https://github.com/mypdns/matrix/assets/108126637/99832b0e-32b4-44b6-9da1-a5b18bb393cb)
![322817191-6ee43d65-34b9-4454-ac0b-d0eb9b641eb0](https://github.com/mypdns/matrix/assets/108126637/e8194ed4-534f-4ee4-9125-25c59034c872)
![322817267-022edbae-8fb4-4ffd-adae-1968d989d381](https://github.com/mypdns/matrix/assets/108126637/c4ef9a5d-59e4-4371-aa2c-5b27fe8cc62a)
![322817399-b4936ee5-5c2f-47dd-ae02-ed761062dba2](https://github.com/mypdns/matrix/assets/108126637/754ebee7-0cda-4b22-88bb-886f70e3f309)
![322817470-84fa2ebb-80c4-4890-a663-96cfcb1d0a19](https://github.com/mypdns/matrix/assets/108126637/01491b09-4e26-49ee-8a67-dc4ce7b4849f)
![322817521-9faedb23-0ce6-4296-b61f-283bb89f7ddb](https://github.com/mypdns/matrix/assets/108126637/33bd49bf-9050-4650-8fe1-efc1001ae3b9)
![322817570-37d3414e-09d7-4f01-9f99-e1d84fe42149](https://github.com/mypdns/matrix/assets/108126637/f927f8d2-5130-44a0-9c09-45659861acbb)
![322817633-5d2c840c-ba1c-44b5-804a-f2c922c88c2a](https://github.com/mypdns/matrix/assets/108126637/ae050ff3-72dd-48d8-b675-1dc9fbba2039)
![322817699-877fad3e-0918-4726-9f6d-68d17e206597](https://github.com/mypdns/matrix/assets/108126637/20666e62-ae28-4193-b6c8-ef33d9a4cd26)

</details>

### Links to external sources

```CSS
https://westernautomobileassembly.com/M3YydzlMOUYxQzR3M1o=
https://westernautomobileassembly.com/M3cyVjliOWwxRDljOVc=
https://westernautomobileassembly.com/M0YydTJvN000ejRqOTg=
https://westernautomobileassembly.com/MzIyMjl0OVk0eDdpN0Y
https://westernautomobileassembly.com/M1IyTjV4OGk5czZYNVE=
https://westernautomobileassembly.com/M2EySzdhOE4zTjJaNVY=
https://westernautomobileassembly.com/M1MyeTlmOVc5NTVMN0w=
https://westernautomobileassembly.com/M3czdTBCMEkwQjc1OHk= 
https://westernautomobileassembly.com/Mmw3WDd3MTc5TDFiNEo=
https://westernautomobileassembly.com/M1UyeTl6OWg2dzBlN0o=
https://westernautomobileassembly.com/M0MyczlZM1MySjBBMUs=
https://westernautomobileassembly.com/M2EzNTBkMHMwYjRpOXk
https://westernautomobileassembly.com/M0UyYjlBODA1cDMxOTI=
https://westernautomobileassembly.com/M2YwZzk2MnYzVjZhNlA=
https://westernautomobileassembly.com/M3cyVzZ3OEIyMTBOOXk=
https://westernautomobileassembly.com/M1QyZDNoOTQxVDNxN20=
https://westernautomobileassembly.com/M1oyUTg2N3U3NDd2N1E= 
https://westernautomobileassembly.com/M2cwVTUxNEIxOTFXM3I=
https://westernautomobileassembly.com/M20zNjBPMDYxQjFiMng=
https://twitter.com/darksamson2/status/1779784028880580627
https://twitter.com/betwaycodes1/status/1779786300289167487
```
```


### logs from uBlock Origin

_No response_

**Comment by g0d33p3rsec** [comment]
Took a look at the root of the domain and noticed this today.
![image](https://github.com/mypdns/matrix/assets/108126637/f4d62dde-1ebc-4d03-9acc-a382e372397f)
![image](https://github.com/mypdns/matrix/assets/108126637/ee165ad6-f38a-4533-a9c7-d4bc5e539c00)

**Comment by spirillen** [comment]
Well you did catch the, up front... and that is good :+1:
