### ISSUE TITLE
azezieldraconous.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#464]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
This site is now hosting the kit that was previously at westernautomobileassembly[.]com, littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, and ajstelecom[.]com[.]mx
```

### Domain records

```CSV
azezieldraconous.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![324566193-0b2d0464-9102-4f31-8d26-978762394637](https://github.com/mypdns/matrix/assets/108126637/4d4e04df-a662-4412-aefd-302819e748cb)
![324567694-9b009aa0-b7a8-491c-b9d7-d99285c0c084](https://github.com/mypdns/matrix/assets/108126637/0044d3d5-f220-42cb-a4d1-7a8e9e4f2fea)
![324568984-a86f70af-89e8-41b9-8d1e-0b245d4ef89d](https://github.com/mypdns/matrix/assets/108126637/0d20f02a-ead4-447a-a3c3-4e29d8506b5d)
![324568620-4c29bdce-6c18-4c23-934f-8cf978387c20](https://github.com/mypdns/matrix/assets/108126637/46c54722-3a38-4436-8030-c73280c8f10c)

</details>

### Links to external sources

```CSS
https://azezieldraconous.com/Mk82RTVaMjg0djE4MVo=
https://azezieldraconous.com/M1czaTBQNmQzUTZnOVM=
https://azezieldraconous.com/M3QzVjBVN1E0YzNSMDQ=
https://azezieldraconous.com/MzYydTVWOGY5WDZTNVo=
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Thanks for your report
