### ISSUE TITLE
safecartusa.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#466]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
This domain is now serving the phishing kit that was previously at foreverfarley[.]com.
```

### Domain records

```CSV
safecartusa.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![326201820-9ed455f8-72e8-4da8-9af3-3a706fccd725](https://github.com/mypdns/matrix/assets/108126637/bc924013-b97d-4409-849c-494a268825db)
![326201851-f7bf8853-1e37-4f36-ab51-f80dea4ac646](https://github.com/mypdns/matrix/assets/108126637/a58662df-89e9-4390-8585-d84f457ff228)
![326201909-55c11694-4037-4d00-a3b3-71bf984871cc](https://github.com/mypdns/matrix/assets/108126637/34391f93-b577-4476-8b32-22389ab70196)
![326201940-53e97f92-ace0-4cb6-9c53-e77db478031e](https://github.com/mypdns/matrix/assets/108126637/ecc8b1a7-a0bb-4318-a694-d2c61e4a2121)
![326201983-3239361c-c3c3-42a0-92f6-a482eeb79586](https://github.com/mypdns/matrix/assets/108126637/087f4f53-4fc3-4e37-853f-2aa5c1feead7)

</details>

### Links to external sources

```CSS
https://safecartusa.com/MzEzVjFINGE4eDFTM3c=
https://safecartusa.com/M1oyajZEMHEycTFDOW4=
https://safecartusa.com/M3cyUTVWOGU5VDVtM3Y=
https://safecartusa.com/M04zMjFZNFM4NjJ5MXQ=
https://safecartusa.com/M0MzeTFTNFo4ZDFVN0I=
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Super, added
