### ISSUE TITLE
jestertunes.com

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#467]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Domain records

```CSV
jestertunes.com|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![327021440-28b6ca5e-67a4-485d-8677-faa283c5031f](https://github.com/mypdns/matrix/assets/108126637/73e19737-99bb-40be-94e2-34d53030c4b4)
![327021470-92d692eb-af43-4184-9e4e-336fafc36bd0](https://github.com/mypdns/matrix/assets/108126637/4ecc2054-cd6d-4e01-9acc-d5d526eb5587)
![327021559-fe513133-d210-425b-87cd-05831443a36e](https://github.com/mypdns/matrix/assets/108126637/f8e85067-188e-4a56-82e0-be7c4d9e4cba)
![327021603-04dd0739-759a-4b88-b373-8b699649cf72](https://github.com/mypdns/matrix/assets/108126637/a145bfae-048c-4912-9fd7-cb03a9cc6860)
![327021648-8228e848-9b76-40f6-9ab1-09137a7edfd5](https://github.com/mypdns/matrix/assets/108126637/d4ddbd39-5cd6-4b22-90d4-170d1c994593)
![327021687-b22db84e-3c27-4bdb-afdf-61398a93700d](https://github.com/mypdns/matrix/assets/108126637/2e761424-c30c-490a-8f31-4e041119a0ab)
![327021717-ade1653c-a99b-4c31-8b3f-cf4f0f825cac](https://github.com/mypdns/matrix/assets/108126637/3fd73d45-56cf-4ba5-9a9d-6ea093729530)
![327021766-f71abe09-c074-41ea-b17a-7b3ace388479](https://github.com/mypdns/matrix/assets/108126637/882c8496-5b54-4bee-879a-14b4df906494)
![327021783-60c3987e-28ac-4c03-9afd-1dd4f2bb7749](https://github.com/mypdns/matrix/assets/108126637/61ee6b31-7e41-4a36-80ae-7a84720bc844)
![327021812-0c28229a-c76a-4878-978d-f00e15bc855c](https://github.com/mypdns/matrix/assets/108126637/8ff82205-5d5a-48d0-97c1-aed5aafef7e6)
![327021861-b18ed1de-da66-4fcc-b452-fdf163d0bddd](https://github.com/mypdns/matrix/assets/108126637/e268a0e6-5db5-44d6-a9d9-dc14d56b641c)

</details>

### Links to external sources

```CSS
https://jestertunes.com/M0MwSDduOUI3VjdyOWI=
https://jestertunes.com/M1gzZDF5NkI4MzZLMmw=
https://jestertunes.com/M3MzWDEzNmw4UDY2MjE=
https://jestertunes.com/M2YzaDF0NjM4RzZwMjA=
https://jestertunes.com/MzgzcjFrNjc4STYyMjc=
https://jestertunes.com/M0ozMDFTNkU4azZIMms=
https://jestertunes.com/M3QxOTMzMjQwaDI0MWI=
https://jestertunes.com/M2wyVjdrM2c1SzhpOFM=
https://jestertunes.com/M0czbTBHN3E0dTMyMHU=
https://jestertunes.com/M1UyejhBNXM4cDhyOXg=
https://jestertunes.com/M3kyZjZ0NTc5ajJQN3o=
https://jestertunes.com/M04yRzZSNUg5NjJ5N3k=
https://jestertunes.com/M08zQzFUODMyYTcxNlU=
https://jestertunes.com/MzYzVjFLNG0wdDZmNXg=
https://jestertunes.com/M0ozYTFwMGQ4QjZVMUU=
https://jestertunes.com/M1YyRDhQMjMwcTVlMG8=
https://jestertunes.com/M0ozcTAwNlYyeTB5NlI=
https://jestertunes.com/M3kzUzEyN0cwOThhN1o
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Thanks, added
