### ISSUE TITLE
carnesboinobre.com.br

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#469]
### Blacklist domain as

- [X] Wildcard, The domain should be entirely blacklisted
- [ ] Subdomain, We should not blacklist the entire domain, only sub-domains
- [ ] Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

### Comments

```markdown
This domain is now hosting the phishing kit that was previously at technowide[.]com[.]tr
```

### Domain records

```CSV
carnesboinobre.com.br|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![330204704-c691e51e-b251-42d8-beb3-c88b9bf7df98](https://github.com/mypdns/matrix/assets/108126637/db02d0ee-8041-4fa3-92f8-c100ae49f9a5)
![330204748-7bd88bcc-f43f-43c6-bb66-b7b134dc1153](https://github.com/mypdns/matrix/assets/108126637/17d77adf-911b-4749-9864-a1354c8e5fb0)
![330204790-a005f57b-f8e5-4778-ac9a-801fe669aefc](https://github.com/mypdns/matrix/assets/108126637/0627f1b6-e63f-4608-a421-400dc2e36764)
![330204846-93ace540-40c0-413f-aeaf-052bd919d835](https://github.com/mypdns/matrix/assets/108126637/a12b2425-9ae2-42ec-aa55-885d2974cab2)

</details>

### Links to external sources

```CSS
https://carnesboinobre.com.br/M0wzeTF0NHY4SDEyM00= 
https://carnesboinobre.com.br/MzkyQjZqNHkyUzZCOU8=
https://carnesboinobre.com.br/M3AyaDVsOGE5aTVrM2I=
https://carnesboinobre.com.br/M1gzRDFoNEI4bDI0MUk=
```
```


### logs from uBlock Origin

_No response_

**Comment by spirillen** [comment]
Thanks for your contribution
