### ISSUE TITLE
confession-best.ru

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#611]
### Comments

While investigating the content on a suspicious image host, ```i.postimg.cc```, I came across this set of similarly structured lure pages which all request the use of a Telegram login.  See also: https://github.com/mitchellkrogza/phishing/pull/427

### Wildcard domain records

```CSV
confession-best.ru|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![2c2f4fd0-1f17-46b5-8360-3b99c50506c7](https://github.com/mypdns/matrix/assets/108126637/5c73abec-23da-4511-9ac7-a7585daf25a3)

</details>

### Links to external sources

```CSS
https://urlscan.io/result/2c2f4fd0-1f17-46b5-8360-3b99c50506c7
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Committed in [d90fb27b827f517d64cf192b7f965599a0f509aa](https://github.com/mypdns/matrix/commit/d90fb27b827f517d64cf192b7f965599a0f509aa) Failed id in commit comment
