### ISSUE TITLE
glitch.me

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#616]
### Comments

While investigating the content on a suspicious image host, ```i.postimg.cc```, I came across a number of malicious subdomains which are being hosted at ```glitch.me```. See also: https://github.com/mitchellkrogza/phishing/pull/429

### Wildcard domain records

```CSV
null
```

### Sub-Domain records

```CSV
discord-fake-nitro-expiriment.glitch.me|phishing
0ffice365-1drvve-oneauthmx1drive.glitch.me|phishing
dobsmore.glitch.me|phishing
faithful-cotton-blue.glitch.me|phishing
rightful-diamond-skiff.glitch.me|phishing
we3bwebma1l-r0unclcube-web3nail-nailweb-deliv3ry.glitch.me|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![342797055-c276f784-9308-4f24-b426-b69bc7ca132f](https://github.com/mypdns/matrix/assets/108126637/2a33651a-2597-40fa-beb2-a4f7bcf7c0a2)
![342797099-be44b5d7-71e0-4ac3-ae4b-21f09b4b3fe1](https://github.com/mypdns/matrix/assets/108126637/358cc6fa-d3e1-4a61-9c8c-3599112229e4)
![342797132-f563d887-a06c-4bb8-9166-218e1b43624b](https://github.com/mypdns/matrix/assets/108126637/6da9704a-14fb-49a6-99eb-791f75a72196)
![342797199-fc6d83b9-34ab-4573-9108-8338a08d4093](https://github.com/mypdns/matrix/assets/108126637/48f3af7d-e620-48cc-acd2-66953cb54c7b)
![342797251-3b51d60d-e4ef-48af-93df-0e36bdda1a87](https://github.com/mypdns/matrix/assets/108126637/492d9cf9-6976-4fda-99e8-a1ca308ebc78)
![342797298-0771b13c-ce2b-40a9-b489-774bbb0a18a7](https://github.com/mypdns/matrix/assets/108126637/79802b96-9da4-4fdf-b792-3ccdd05b149d)
![342797380-29fca187-f167-49c4-8892-7fd40d5c0bef](https://github.com/mypdns/matrix/assets/108126637/831a8033-0def-4c15-8a5e-5b631a35b358)

</details>

### Links to external sources

```CSS
https://urlscan.io/result/547fbfea-9dc0-419f-828a-01e2ccdce7bc/
https://www.virustotal.com/gui/url/07ebe6f10ffbf80f27b5112cda10254c6320703dea8aac8cfd32d80bc2238a3b
https://urlscan.io/result/b62e8401-8a3e-4c82-b903-49ae06014aea/
https://www.virustotal.com/gui/url/fd2045b883fd1cea4d33ea6a65f038eca7d9b844c3c0adc14c1d6a5fad5c3f7f
https://urlscan.io/result/1b6eaf6f-feb1-4be5-8b71-2eaecb786739/
https://www.virustotal.com/gui/url/8490d245db066a39c78b1920ee504f66c27ddabd4369c05250372b61bfb7e51f
https://urlscan.io/result/18aeb966-a059-4b0e-93e9-a16782e3fe43/
https://www.virustotal.com/gui/url/f9f98836815f2e04d4ba4054f4f3a1505ef6b0a3654cda9fd185480d060c2235
https://urlscan.io/result/24b753ec-a712-4c65-bf57-1d5ebe8350c5/
https://www.virustotal.com/gui/url/bec9d74be511f572beeb5011375523b277fc55098dc3b7f1dfb4d13380207a18
https://urlscan.io/result/cc4dc9e1-6477-4d3e-954c-5e9a5e886315/
https://www.virustotal.com/gui/url/00d68a2516ebc571352e158ce0af28b3f55964efce1b8acf5a4c0a2887584404
https://urlscan.io/result/7f81228c-c69d-4009-ad12-c2a4dcab323c/
https://www.virustotal.com/gui/url/3f41ee9ebf944c08886eed738cb24112c4633e9693a5ef34eaabf49748903aac?nocache=1
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
This one went to wrong issue :)

```csv
item-trck-uk-royal-mail.dmaqpay.com.br|phishing
```
