### ISSUE TITLE
polyfill.io

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#620]
### Comments

> The new Chinese owner of the popular Polyfill JS project injects malware into more than 100 thousand sites. - `https://sansec.io/research/polyfill-supply-chain-attack`

### Wildcard domain records

```CSV
polyfill.io|malicious,tracking
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
null
```

### SeafeSearch records

```CSV
null
```

### Screenshots

N/A

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
@ShadowWhisperer you might like to add this one to your malware list

**Comment by ShadowWhisperer** [comment]
Already under **Tracking**. 👍

**Comment by spirillen** [comment]
Thanks for the info :+1:
