### ISSUE TITLE
shrtm.nu

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#624]
### Comments

According to @floschliep, the domain owner, there should be no phishing on the domain. However a simple search on the domain shows, that their historically at least seems to have been phishing.

The domain is listed with the following records

This domain redirects to `link.shortmenu.com`, which means it is only RFC:953 blacklists who needs this record #625

```
data/UltimateHostsBlacklist2.txt:shrtm.nu
data/hphosts/psh/domain.list:shrtm.nu
data/hphosts/psh/domain.list:www.shrtm.nu
```

And the apparently no longer maintained project `blocklistproject/list`

### Wildcard domain records

```CSV
shrtm.nu|phishing,redirector
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
null
```

### SeafeSearch records

```CSV
null
```

### Screenshots

N/A

### Links to external sources

```CSS
https://github.com/blocklistproject/Lists/pull/1252
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
To @floschliep, you can try searching https://hosts.ubuntu101.co.za/app/contents/ to find the upstream projects that hosts your domain within [UltimateHostsBlacklist](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist), however the search domain seems down to me

**Comment by floschliep** [comment]
@spirillen Will do (…once the domain is online again), thanks a ton. I'll monitor the other issues you opened, super helpful.

For what it's worth – taking a quick look at this project's README, url shortener domains such as shrtm.nu IMO fall into the whitelist-case due to hosting only user-submitted content. What do you think?

**Comment by spirillen** [comment]
As you would have been reading in the [FAQ](https://github.com/mypdns/matrix?tab=readme-ov-file#faq), We do only use the [whitelist](https://github.com/mypdns/matrix?tab=readme-ov-file#whitelist) within MyPDNS for our own purposes. All whitelisting is a personal matter, for where @mypdns have nothing to do.

https://github.com/mypdns/matrix?tab=readme-ov-file#whitelist-1

-------

However, you are always welcome to spread your thought, to share it with everyone out there on the catNet :dog2: 

We love democracy and right to freedom, so please just do speak and give your arguments.

--------

**Comment by spirillen** [comment]
> That's not what I got from reading the FAQ,

Thanks for sharing this info, it can help writing better text. Could you please tell me which parts that you find troublesome?
