### ISSUE TITLE
reluzformaturas.com.br

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#626]
### Comments

This domain is now hosting the phishing kit that previously at abcmueblesbogota[.]com, ergoterapiacaribu[.]ch, ijconnects[.]com, cbcaps[.]shop, bersowir[.]org, brunotasso[.]com[.]br, cantabriaeventos[.]com, wisbechguide[.]uk, pescacancun[.]com, bkengineersindia[.]com, englishplusmore[.]com, carnesboinobre[.]com[.]br, technowide[.]com[.]tr, jestertunes[.]com, safecartusa[.]com, foreverfarley[.]com, azezieldraconous[.]com, westernautomobileassembly[.]com, littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, ajstelecom[.]com[.]mx, and many others (approximately 130 domains since 2021).

### Wildcard domain records

```CSV
reluzformaturas.com.br|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![345189718-f18af28d-18d1-4718-b81b-6f4ae45b886e](https://github.com/mypdns/matrix/assets/108126637/d92a848a-db59-4635-9b04-6530f46cf8ef)
![345189812-324339b9-a9ed-4471-8afa-4f02b5508d87](https://github.com/mypdns/matrix/assets/108126637/7105d538-7f2f-4f83-a70e-eea098608f4d)

</details>

### Links to external sources

```CSS
https://reluzformaturas.com.br/M2syODhKMnA2SjgzM2M=
https://reluzformaturas.com.br/M0ozODFCOWg5bTZGM0s=
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Sorry for the merge delay...

**Comment by spirillen** [comment]
committed in 15376f9a2473
