### ISSUE TITLE
ucnlkw.cyou

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#628]
### Comments

This site is hosting a US Postal Service delivery failure scam page.

### Wildcard domain records

```CSV
ucnlkw.cyou|phishing
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```css
usxd.ucnlkw.cyou|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![345244366-6a53a29d-ee4c-4d54-837c-34a3784ad23c](https://github.com/mypdns/matrix/assets/108126637/5b385db2-8538-4be0-a018-cdabe18d9338)

</details>

### Links to external sources

```CSS
https://github.com/mitchellkrogza/phishing/pull/438
https://urlscan.io/result/476e1358-4b2b-49b1-be7e-65d5e326af2a/
https://www.virustotal.com/gui/url/5fc6d9e93e863d42acaadd9e2b30c5a36af495d0d3ccaa2062330bc929b9fe68
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Committed in 7f12ee768ed40b68557b65f675f44ccc68e1254e
