### ISSUE TITLE
playwell.ug

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#670]
### Comments

This domain is associated with #650.  See also: https://github.com/mitchellkrogza/phishing/pull/446

### Wildcard domain records

```CSV
playwell.ug|malicious
```

### Screenshots

<details><summary>Screenshot</summary>

</details>

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
92f0b45e423f54d5d6caae5ea9d206ff41850a4e
