### ISSUE TITLE
45.9.74.32 - StrellaStealer

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#707]
### Comments

This IP is being used to distribute StrellaStealer.  

See also: https://github.com/mitchellkrogza/phishing/pull/453

### Wildcard domain records

```CSV
32.32.74.9.45|malicious
```

### Screenshots

<details><summary>Screenshot</summary>

</details>

### Links to external sources

```CSS
http://45.9.74.32:8888/904.dll
https://urlscan.io/result/e422a6fd-3185-4a9f-9074-226ffb595eb2
https://www.virustotal.com/gui/file/3a9910505be76c9bcbad15e85d0940e4024b55904064ace74aa888eeefd29f37
http://45.9.74.32:8888/993.dll
https://urlscan.io/result/cf2389b3-2d36-442e-8183-1ebf15d5f9cd/
https://www.virustotal.com/gui/file/84399d751b639182ffede01f3366cea17af7797e8e4b6a1c4fe21ca9d66bc457
http://45.9.74.32:8888/2945.dll
https://urlscan.io/result/cd7d4df4-ce7d-451b-bc9f-dae4bb22fd20
https://www.virustotal.com/gui/file/ce29306eb568ab557218f054bcf68d19df3c09a7a9102589eea59b65affebe27
http://45.9.74.32:8888/3107.dll
https://urlscan.io/result/a06cff3e-39f1-498f-b410-9a3d0b7b3263/
https://www.virustotal.com/gui/file/a28a7418ac1cf027e8b5e631204255b02081f2156aa53ed46d137608ca11e400
http://45.9.74.32:8888/3272.dll
https://urlscan.io/result/d2c6311a-7e65-4971-9f07-b1501f947c05
https://www.virustotal.com/gui/file/f6a424b96c283def5f68836158c2f3c599cf68fdbd6f21eb25055206aa55699f
http://45.9.74.32:8888/3290.dll
https://urlscan.io/result/88d8a0bb-144a-4254-92ef-79651660cf18
https://www.virustotal.com/gui/file/c0e7dc565958caded1fe7634cd0ce0e2c1b0657b45bc7d5666df807848e03271
http://45.9.74.32:8888/3682.dll
https://urlscan.io/result/bf0a832f-5404-4a6b-991b-2e8533e93835/
https://www.virustotal.com/gui/file/d94d3b3bece35e167b56429cc22ad7000ceb9d973bed7578c737a2316df1f32d
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
> StrelaStealer seeks to extract email account log-in credentials. At the time of writing, this program targets Microsoft Outlook and Mozilla Thunderbird email clients.
> 
> Following successful infiltration, StrelaStealer searches for "logins.json" (account/password) and "key4.db" (password database) within the "%APPDATA%\Thunderbird\Profiles\" directory - by doing so, it can acquire the credentials for Thunderbird.
> 
> Alternatively, if Outlook credentials are targeted - StrelaStealer seeks out the Windows Registry from where it can retrieve the program's key and "IMAP User", "IMAP Server", as well as the "IMAP Password" values. Since the latter is kept in an encrypted form, the malicious program employs the Windows CryptUnprotectData feature to decrypt it prior to exfiltration.
