### ISSUE TITLE
lebomashilo.co.za

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#737]
### Comments

This domain is now hosting the phishing kit that previously at intrinsicisle[.]za[.]com, reluzformaturas[.]com[.]br, abcmueblesbogota[.]com, ergoterapiacaribu[.]ch, ijconnects[.]com, cbcaps[.]shop), bersowir[.]org, brunotasso[.]com[.]br, wisbechguide[.]uk, pescacancun[.]com, bkengineersindia[.]com, englishplusmore[.]com, carnesboinobre[.]com[.]br, technowide[.]com[.]tr, jestertunes[.]com, safecartusa[.]com, foreverfarley[.]com, azezieldraconous[.]com, westernautomobileassembly[.]com, littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, ajstelecom[.]com[.]mx, and others (more than 130 domains since 2021).

### Wildcard domain records

```CSV
lebomashilo.co.za|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![351924094-ab61429f-7c17-4ef2-9724-81826ff85208](https://github.com/user-attachments/assets/89bcfbbf-0c4f-4653-b7e4-62ef167ec6ca)
![351924115-8075b037-5256-4ee8-9dea-1215dfca219d](https://github.com/user-attachments/assets/7e287cf8-f905-4ded-8715-f3793f3dd13c)
![351924151-b6df09e9-7295-4807-86c6-29b196942475](https://github.com/user-attachments/assets/570f2769-fc29-4370-a0a7-d2aa55e07c42)
![351924167-b62ceeca-b368-4fee-8a4f-4be5bad3b21d](https://github.com/user-attachments/assets/45126079-e4bc-4f7a-89c7-eac85d27a6c1)
![351924207-15b87904-2685-4875-af70-f759891f71d3](https://github.com/user-attachments/assets/e8dd70a7-b861-42de-bdc7-2266f982e9e4)
![351924392-f3c94a9e-5655-4674-a734-22af89ae3509](https://github.com/user-attachments/assets/ce4b03b7-cb25-41ed-b0ac-ddd880940f15)
![351924432-d9a8f15e-7770-44c2-934e-4bf8b5bd9562](https://github.com/user-attachments/assets/56a085d9-a1e8-44f3-9570-a12ce55f35bd)
![351924482-2f683e42-53f3-41ec-aaa1-1dd7c3d6032c](https://github.com/user-attachments/assets/8e5f38b2-a6af-4b4d-bbe2-70e74934f6b2)

</details>

### Links to external sources

```CSS
https://lebomashilo.co.za/M20zSDV3Mk8zaTJIOGs= 
https://lebomashilo.co.za/M24xbzNaMlowVTI2MTc=
https://lebomashilo.co.za/M0g0MjNiNmM2ZjV3OW0=
https://lebomashilo.co.za/MzgyYTkyOWc4WTdlMFA=
https://lebomashilo.co.za/M1o0VTJHNHg1RTFEOE0=
https://lebomashilo.co.za/M1U0cTNBOEI5YTJhNFg= 
https://lebomashilo.co.za/MU8wQzdxMHc3bDdTMno=
https://lebomashilo.co.za/M2Q0djVGNXc2ODMzOXM=
https://lebomashilo.co.za/M2YwMTlMMVA1VjFGMzA=
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
committed in ea99c511ce6b59f7386eab2323eb835d2209df73
