### ISSUE TITLE
vonderlee.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#778]
### Comments

Hi @d-Rickyy-b Is it possible you could posts the source code of that email from the screenshot?

Credit: https://github.com/d-Rickyy-b

### Wildcard domain records

```CSV
vonderlee.com|
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
null
```

### SeafeSearch records

```CSV
null
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/20c3f50a-bb19-4541-85bc-dc6727d4bcd4)

</details>

### Links to external sources

```CSS
https://github.com/badmojr/1Hosts/issues/1816
```

### logs from uBlock Origin

N/A

**Comment by d-Rickyy-b** [comment]
Hi, sure will do when I'm back home later.

**Comment by d-Rickyy-b** [comment]
I created a zip archive with two mails. The one is the mail from the screenshot. This one was about the huberwills[.]com domain.

I attached another mail that was sent from the vonderlee[.]com domain. Also I redacted some information about my email server and receiving account.

[emails.zip](https://github.com/user-attachments/files/16550979/emails.zip)

**Comment by spirillen** [comment]
Super, thanks a lot, that help keeping the project up to date.
