### ISSUE TITLE
sbic.com.br

### ISSUE THREAD

**Issue by g0d33p3rsec** [mypdns/matrix#792]
### Comments

This domain is now hosting the phishing kit that previously at squad[.]cl, benyex[.]cl, lebomashilo[.]co[.]za, intrinsicisle[.]za[.]com, reluzformaturas[.]com[.]br, abcmueblesbogota[.]com, ergoterapiacaribu[.]ch, ijconnects[.]com, cbcaps[.]shop), bersowir[.]org, brunotasso[.]com[.]br, wisbechguide[.]uk, pescacancun[.]com, bkengineersindia[.]com, englishplusmore[.]com, carnesboinobre[.]com[.]br, technowide[.]com[.]tr, jestertunes[.]com, safecartusa[.]com, foreverfarley[.]com, azezieldraconous[.]com, westernautomobileassembly[.]com, littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, ajstelecom[.]com[.]mx, and others

### Wildcard domain records

```CSV
sbic.com.br|phishing
```

### Screenshots

<details><summary>Screenshot</summary>

![363820123-c4bfbb07-92a6-4ebe-9b25-fcdc1767ef5e](https://github.com/user-attachments/assets/dcae377e-f113-4828-a9a9-5e384e7ce11a)
![363820242-cbc78b05-68e4-45b5-9c10-1ac18cfa7f0b](https://github.com/user-attachments/assets/8929d495-25c6-456c-9a6f-f8323c09af3e)
![363820279-58e9330c-7830-4387-8739-985a843313de](https://github.com/user-attachments/assets/4ab31cfc-2905-438e-8857-55e84d58dbbd)
![363820745-0a0fa4cd-e563-4611-b6d5-dd62246f94ee](https://github.com/user-attachments/assets/5cf96e61-e8ee-433b-8e46-d0fe41b86367)
![363820827-f94fd4cd-7ba4-4448-9557-5740785dc4a1](https://github.com/user-attachments/assets/3e6ff209-6c6f-4217-b13a-98c685212694)
![363820887-593b492d-34dc-4c4f-96f6-ee69fc67adaf](https://github.com/user-attachments/assets/519581d9-c7ed-4148-8f37-a2bbd7b5e872)
![363821005-9a59b6ff-d9c7-4942-8a9f-d8bad7bd2ce8](https://github.com/user-attachments/assets/9b4738bc-420c-40a3-a083-2ef7bc05fa37)
![363821076-56895fcb-2c3f-4ea9-8276-f4bc297db4ff](https://github.com/user-attachments/assets/f6deccfc-068c-4613-8fb1-1bf04ab30790)
![363821133-1de40170-6311-4255-84f5-7d1f4046ea74](https://github.com/user-attachments/assets/605d2e0b-4750-4941-aa36-0422eaddb1e3)
![363821201-d563892b-a741-4a57-934c-99c5e0d88fb2](https://github.com/user-attachments/assets/c6339756-d5a2-42e1-a409-8981ddbee5bb)
![363821290-4717c9a5-cfe5-4eda-92ec-f0c2dbcc380a](https://github.com/user-attachments/assets/7c5bf2dd-a687-4ffd-b0f8-d4d68e09e107)
![363821343-7e3f5353-6258-422a-99d7-682a3f1e0258](https://github.com/user-attachments/assets/f855df44-640f-4a83-ba9e-a04cd26cc255)
![363821477-8f32506c-72a7-4c43-9318-21148984031b](https://github.com/user-attachments/assets/f0c44671-21b3-443b-a287-8ed23cb28f3c)
![363821573-11e4831d-9d1d-4b1e-afdb-94fae9f9a278](https://github.com/user-attachments/assets/18b46c7f-8cce-465e-9975-3232c95fbcca)
![363821718-5f7e4161-d0a3-436a-a665-8a9eef0d8a70](https://github.com/user-attachments/assets/245c13d8-8a66-46ba-b4cd-9d3a451436ab)

</details>

### Links to external sources

```CSS
https://mail.sbic.com.br/M0EzUjQyMHA0YzFuOE4=
https://mail.sbic.com.br/M0U0RDVVNm01OTdtMjE= 
https://mail.sbic.com.br/M2Q1VjBlMUg3QTI5NGc=
https://mail.sbic.com.br/M0s0ODVuNlI1aDdTMnE=
https://mail.sbic.com.br/M0Q0MzlHMWM5cjg3OUw=
https://mail.sbic.com.br/M280bTU3NWswTzRpMzc=
https://mail.sbic.com.br/M2kycjhBNnUzeTlpNTE=
https://mail.sbic.com.br/M3k1NjFyNWY1dzZvMHI=
https://mail.sbic.com.br/M1c0TDlkOFI1aDhFNzc=
https://mail.sbic.com.br/M1AzRDJxM2EwdDJ0NGY= 
https://mail.sbic.com.br/M0QyZTlmMUYxRDZENE8=
https://mail.sbic.com.br/M1E1aDFBNW02WjN6MUE=
https://mail.sbic.com.br/M2ozeTVFNEc1ZjNXN3Y=
https://mail.sbic.com.br/M0M1TDF4NTk5djZlMkg=
https://mail.sbic.com.br/M240VjZPMEszWjRQNXo=
https://mail.sbic.com.br/M1g1aTF4NXk1MDEyOHg=
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Hello my friend, nice to see you back. I have been afraid you had found other projects to support as you have been silence for a period. 

Hoping everything is well as your end

**Comment by g0d33p3rsec** [comment]
> Hello my friend, nice to see you back. I have been afraid you had found other projects to support as you have been silence for a period.
> 
> Hoping everything is well as your end

Thanks.  All is well, just busy again.  How have you been?

**Comment by spirillen** [comment]
> How have you been?

2 damned hot, thinking about taking a few days into the Hell to cool down a bit, It is as hot as in Phonix the past weeks in little DK... Again coursed by the Russian (weather) 🌞  but got my issue board back up, as someone stumbled on the right solution of deleting the docker config 😕 

Nice to see you back
